{% set name = "libcramjam" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://static.crates.io/crates/libcramjam/libcramjam-{{ version }}.crate
  sha256: 68807397f8ea72def15d33d5dc4ff42abb728dc38a9458a5c55810a59a4553e0

build:
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config                 # [unix]
    - cargo-bundle-licenses
    - cargo-c

test:
  commands:
    - test -e $PREFIX/include/cramjam/cramjam.h              # [unix]
    - test -e $PREFIX/lib/libcramjam${SHLIB_EXT}                      # [unix]
    - if not exist %LIBRARY_INC%\\cramjam\\cramjam.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cramjam.dll exit 1         # [win]

about:
  home: https://crates.io/crates/libcramjam
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  summary: Library combining a plethera of compression algorithms in a similar as possible API
  doc_url: https://docs.rs/libcramjam
extra:
  recipe-maintainers:
    - milesgranger
